# config/config.yaml

# Runs table
runs_table: example/example_runs_table.tsv

# Base directory containing runs
base_dir: example/example_runs

# Approximate memory (in MB) each organ-specific feature extraction / prediction job will require.
memory_extract_generic_mb: 1000
memory_extract_organsp_mb: 1000
memory_predict_organsp_mb: 1000
gpu: 1

###---CONFIGS BELOW ARE NOT RUN-SPECIFIC. DO NOT CHANGE ONCE SET UP FOR A NEW MACHINE---###

# Directory from which regulome_search_organ.py must be run
gds_dir: /mnt/md0/genomic-data-service

# Directory from which run_sei.py must be run
sei_dir: /nfs/boylelab_turbo/rintsen/Sei

# Path to bigwigs
dnase_sig_path: /mnt/md0/DNase_quantile/data_results/all
chip_sig_path: /mnt/md0/ChIP_quantile/data_results
organsp_dnase_sig_path: /mnt/md0/DNase_quantile/data_results/organ_sp

# Resources
organ_list_path: resources/organ_list.txt
total_num_path: resources/total_num/
organ_mapping_json: resources/organ_list_underscore_mapping.json

# Directory containing pickled model files for TLand, TLand-light, and TLand-lightest
models_path: /nfs/boylelab_turbo/rintsen/TLand_resources/models